### ISSUE TITLE
GetLastError

### ISSUE THREAD

**Issue by MrWarLock** [MahdiSafsafi/delphi-detours-library#37]
It is normal that can't GetLastError procedure Hooked ? (win32 api)
I'm using latest Lazarus version

  // --------------------------- GetLastError
var  TpGetLastError: function:DWORD; stdcall = nil;   

function InGetLastError: DWORD; stdcall;
Begin
  showmessage('Hooked');
  Result := TpGetLastError;
end;

 // GetLastError
if not Assigned(TpGetLastError) then
    @TpGetLastError := InterceptCreate('Kernel32.dll', 'GetLastError', @InGetLastError , true); // ERROR!!
// @TpGetLastError := InterceptCreate(@GetLastError, @InGetLastError); // ERROR TOO!!
 

i got a SIGILL error in the file: DDetours.pas
function TIntercept.AddHook
NxHook := AllocMem(TrampoSize);     <------ SIGILL error

Thanks for the support

**Comment by MahdiSafsafi** [comment]
Hi MrWarLock,

GetLastError function is widely used by standard Win32Api,VCL functions,even with DDL (indirect way).
When you install your hook on GetLastError function ... DDL starts the job and it may happen that it uses GetLastError (indirect way throught others Win32Api used by DDL core) So you must insure that TpGetLastError will get initialized before InterceptCreate terminates it's job.
Here's the correct way to hook GetLastError function.
```
var
  TpGetLastError: function: DWORD;stdcall = nil;
  nTime: Integer = 0;

function InGetLastError: DWORD; stdcall;
Begin
  inc(nTime);
  Result := TpGetLastError;
end;

procedure TForm1.Button1Click(Sender: TObject);
begin
  GetLastError;
  Caption := IntToStr(nTime);
end;

initialization

if not Assigned(TpGetLastError) then
  InterceptCreate(@GetLastError, @InGetLastError, @TpGetLastError);

finalization

InterceptRemove(@TpGetLastError);

end.
```

PS:
- Be aware ! GetLastError is WIDELY USED with Win32Api,VCL,RTL,.. You take the risk to slowdown your app !
- If you call others functions such ShowMessage in InGetLastError, your app risks to enter in infinite loop because : The hooked GetLastError will call ShowMessage and ShowMessage will call GetLastError and so on !

Mahdi.
