### ISSUE TITLE
API CloseHandle or NtClose will cause the program to crash

### ISSUE THREAD

**Issue by sqlnew** [MahdiSafsafi/delphi-detours-library#39]
Hi, first thanks to your delphi-detours-library project, it help me a lot.
I use it on the global hook , it work good and stable, but when i hook the API:
CloseHandle or NtClose , it will cause the program to crash(the target process crash).
I do not know what causes it. and can you fix this problem? 
Thank you very much!

**Comment by MahdiSafsafi** [comment]
Hi sqlnew,
Some functions require threads to be stopped before installing the hook.
Did you try to englobe your hook into BeginHooks/EndHooks function ?

**Comment by sqlnew** [comment]
Hi MahdiSafsafi,
Thanks your tips and advice, this method is not used in the examples, so i have not used it.
I will test BeginHooks/EndHooks function , and i will give the results back.

**Comment by sqlnew** [comment]
Hi MahdiSafsafi,
I have tested, and add keywords BeginHooks function, when the hook CloseHandle or NtClose when the target program during normal operation, there is no exception, but the crash when the target program quit (i test the notepad.exe), I do not know the specific cause of the problem. My test environment was windows2008R2 x64. Could you help solve, thank you very much.

**Comment by MahdiSafsafi** [comment]
Hi again, 
First, you should know that this error is not related to DDetours library ... It's related to the way you are using (hooking) CloseHandle function.
When installing hook on CloseHandle, it happens that some thread calls CloseHandle ... and that can cause a crash ... To solve that, you need to suspend all threads (except the thread that is trying to install the hook) ... That's an easy task ... All what you need to do is to englobe your hook into BeginHooks/EndHooks frame ... This tells DDL to suspend all threads first before installing your hook ... and restoring (resuming) suspend threads once the hook is installed.
Now, when your app is terminating, it happens again that your app frees DDL first and later it calls CloseHandle function ... And since DDL was freed a call to HookedCloseHandle will result in an AV error.
So, you need to unhook before your app get terminated and yes this time you need to use BeginUnHooks/EndUnHooks frame.
Here is a simple code that I wrote and runs without problem:
```
var
  TampolineCloseHandle: function(hObject: THandle): BOOL;stdcall = nil;

function CloseHandleHook(hObject: THandle): BOOL; stdcall;
begin
  Result := TampolineCloseHandle(hObject);
end;

initialization
BeginHooks;
@TampolineCloseHandle := InterceptCreate(@CloseHandle, @CloseHandleHook);
EndHooks;

finalization
if Assigned(TampolineCloseHandle) then
begin
  BeginUnHooks;
  InterceptRemove(@TampolineCloseHandle);
  EndUnHooks;
end;
```
Have a nice day.
Mahdi.

**Comment by sqlnew** [comment]
Hey, good news, follow your tips, in the Global HOOK  I monitor the target process. When the process before quitting, i perform a BeginUnHooks, InterceptRemove, complete uninstall the hook function, after doing so, CloseHandle. Ntclose has, will not cause the program to collapse.  I am very satisfied with this result. 
In addition, DDetours able COM function also has good support.
This library is useful, and more easy to use than EasyHOOK.  Thank you for this work, we really hope you can continue the Delphi library, and to fix bugs.
At present, the good use and powerful Delphi library has been very little.

**Comment by MahdiSafsafi** [comment]
Nice to hear that you found DDL useful. And yes I'm going to keep developing DDetours and fix bugs if found.
